# Joining Data in SQL

In [12]:
!conda install -yc conda-forge ipython-sql

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

In [13]:
%%capture
%load_ext sql
%sql sqlite:///factbook-join.db

In this mission, we're going to be using a version of the CIA World Factbook (Factbook) database from the guided project from the SQL Fundamentals course. To refresh your memory, this database had one table called facts, where each row represented a country from the Factbook.

In [36]:
%%sql
Select * from facts
limit 5;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[(1, 'af', 'Afghanistan', 652230, 652230, 0, 32564342, 2.32, 38.57, 13.89, 1.51),
 (2, 'al', 'Albania', 28748, 27398, 1350, 3029278, 0.3, 12.92, 6.58, 3.3),
 (3, 'ag', 'Algeria', 2381741, 2381741, 0, 39542166, 1.84, 23.67, 4.31, 0.92),
 (4, 'an', 'Andorra', 468, 468, 0, 85580, 0.12, 8.13, 6.96, 0.0),
 (5, 'ao', 'Angola', 1246700, 1246700, 0, 19625353, 2.78, 38.78, 11.49, 0.46)]

### Inner joins

In addition to the facts table we've added a new table, called cities which contains information on major urban areas from countries in the Factbook (for the rest of this mission, we'll use the word 'cities' to mean the same as 'major urban areas'). Let's take a look at
a description of what each column represents:

- id - A unique ID for each city.
- name - The name of the city.
- population - The population of the city.
- capital - Whether the city is a capital city: 1 if it is, 0 if it isn't.
- facts_id - The ID of the country, from the facts table.

In [35]:
%%sql
Select * from cities
limit 5;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[(1, 'Oranjestad', 37000, 1, '216'),
 (2, "Saint John'S", 27000, 1, '6'),
 (3, 'Abu Dhabi', 942000, 1, '184'),
 (4, 'Dubai', 1978000, 0, '184'),
 (5, 'Sharjah', 983000, 0, '184')]

The last column is of particular interest to us, as it is a column of data that also exists in our original facts table. This link between tables is important as it's used to combine the data in our queries.

The most common way to join data using SQL is using an inner join. The syntax for an inner join is:

SELECT [column_names] FROM [table_name_one]

INNER JOIN [table_name_two] ON [join_constraint];

The inner join clause is made up of two parts:

- INNER JOIN, which tells the SQL engine the name of the table you wish to join in your query, and that you wish to use an inner join.
- ON, which tells the SQL engine what columns to use to join the two tables.

Joins are usually used in a query after the FROM clause. Let's look at a basic inner join where we combine the data from both of our tables.

In [15]:
%%sql
SELECT * FROM facts
INNER JOIN cities ON cities.facts_id = facts.id
LIMIT 5;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[(216, 'aa', 'Aruba', 180, 180, 0, 112162, 1.33, 12.56, 8.18, 8.92, 1, 'Oranjestad', 37000, 1, '216'),
 (6, 'ac', 'Antigua and Barbuda', 442, 442, 0, 92436, 1.24, 15.85, 5.69, 2.21, 2, "Saint John'S", 27000, 1, '6'),
 (184, 'ae', 'United Arab Emirates', 83600, 83600, 0, 5779760, 2.58, 15.43, 1.97, 12.36, 3, 'Abu Dhabi', 942000, 1, '184'),
 (184, 'ae', 'United Arab Emirates', 83600, 83600, 0, 5779760, 2.58, 15.43, 1.97, 12.36, 4, 'Dubai', 1978000, 0, '184'),
 (184, 'ae', 'United Arab Emirates', 83600, 83600, 0, 5779760, 2.58, 15.43, 1.97, 12.36, 5, 'Sharjah', 983000, 0, '184')]

- INNER JOIN cities - This tells the SQL engine that we wish to join the cities table to our query using an inner join.
- ON cities.facts_id = facts.id - This tells the SQL engine which columns to use when joining the data, following the syntax table_name.column_name.

This query gives us all columns from both tables and every row where there is a match between the `id` column from `facts` and the `facts_id` from `cities`, limited to the first 5 rows.

An inner join works by including only rows from each table that have a match as specified using the ON clause

Our inner join will include:

- Rows from the cities table that have a cities.facts_id that matches a facts.id from facts.
Our inner join will not include:

- Rows from the cities table that have a cities.facts_id that doesn't match any facts.id from facts.
- Rows from the facts table that have a facts.id that doesn't match any cities.facts_id from cities.

### Aliases

In the SQL fundamentals course, we learned how to use `aliases` to specify custom names for columns, eg:

SELECT AVG(population) AS AVERAGE_POPULATION

We can also create aliases for table names, which makes queries with joins easier to both read and write. Instead of:

SELECT * FROM facts
INNER JOIN cities ON cities.facts_id = facts.id

We can write:

SELECT * FROM facts AS f
INNER JOIN cities AS c ON c.facts_id = f.id

Just like with column names, using AS is optional. We can get the same result by writing:

SELECT * FROM facts f
INNER JOIN cities c ON c.facts_id = f.id

We can also combine aliases with wildcards - for instance, using the aliases created above, c.* would give us all columns from the table cities.

While our query from the previous screen included both columns from the ON clause, we don't need to use either column from our ON clause in our final list of columns. This is useful as it means we can show only the information we're interested in, rather than having to include the two join columns every time.

In [17]:
%%sql
SELECT c.*, f.name AS country_name FROM facts AS f
INNER JOIN cities AS c ON c.facts_id = f.id
LIMIT 5;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[(1, 'Oranjestad', 37000, 1, '216', 'Aruba'),
 (2, "Saint John'S", 27000, 1, '6', 'Antigua and Barbuda'),
 (3, 'Abu Dhabi', 942000, 1, '184', 'United Arab Emirates'),
 (4, 'Dubai', 1978000, 0, '184', 'United Arab Emirates'),
 (5, 'Sharjah', 983000, 0, '184', 'United Arab Emirates')]

Write a query that:
- Joins cities to facts using an INNER JOIN.
- Uses aliases for table names.
- Includes, in order:
    - All columns from cities.
    - The name column from facts aliased to country_name.
- Includes only the first 5 rows.

In [18]:
%%sql
SELECT c.*, f.name AS country_name 
FROM facts AS f
INNER JOIN cities AS c ON c.facts_id = f.id
LIMIT 5;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[(1, 'Oranjestad', 37000, 1, '216', 'Aruba'),
 (2, "Saint John'S", 27000, 1, '6', 'Antigua and Barbuda'),
 (3, 'Abu Dhabi', 942000, 1, '184', 'United Arab Emirates'),
 (4, 'Dubai', 1978000, 0, '184', 'United Arab Emirates'),
 (5, 'Sharjah', 983000, 0, '184', 'United Arab Emirates')]

Write a query that uses an INNER JOIN to join the two tables in your query and returns, in order:
- A column of country names, called country.
- A column of each country's capital city, called capital_city

In [20]:
%%sql
SELECT f.name country, c.name capital_city 
FROM cities c
INNER JOIN facts f on f.id = c.facts_id
WHERE c.capital = 1;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[('Aruba', 'Oranjestad'),
 ('Antigua and Barbuda', "Saint John'S"),
 ('United Arab Emirates', 'Abu Dhabi'),
 ('Afghanistan', 'Kabul'),
 ('Algeria', 'Algiers'),
 ('Azerbaijan', 'Baku'),
 ('Albania', 'Tirana'),
 ('Armenia', 'Yerevan'),
 ('Andorra', 'Andorra La Vella'),
 ('Angola', 'Luanda'),
 ('American Samoa', 'Pago Pago'),
 ('Argentina', 'Buenos Aires'),
 ('Australia', 'Canberra'),
 ('Austria', 'Vienna'),
 ('Anguilla', 'The Valley'),
 ('Bahrain', 'Manama'),
 ('Barbados', 'Bridgetown'),
 ('Botswana', 'Gaborone'),
 ('Bermuda', 'Hamilton'),
 ('Belgium', 'Brussels'),
 ('Bahamas, The', 'Nassau'),
 ('Bangladesh', 'Dhaka'),
 ('Belize', 'Belmopan'),
 ('Bosnia and Herzegovina', 'Sarajevo'),
 ('Bolivia', 'La Paz'),
 ('Burma', 'Rangoon'),
 ('Benin', 'Porto-Novo'),
 ('Belarus', 'Minsk'),
 ('Solomon Islands', 'Honiara'),
 ('Brazil', 'Brasilia'),
 ('Bhutan', 'Thimphu'),
 ('Bulgaria', 'Sofia'),
 ('Brunei', 'Bandar Seri Begawan'),
 ('Burundi', 'Bujumbura'),
 ('Canada', 'Ottawa'),
 ('Cambodia', 'Phnom Penh'),
 ('Chad', "N'Djamena"),
 ('Sri Lanka', 'Colombo'),
 ('Congo, Republic of the', 'Brazzaville'),
 ('Congo, Democratic Republic of the', 'Kinshasa'),
 ('China', 'Beijing'),
 ('Chile', 'Santiago'),
 ('Cayman Islands', 'George Town'),
 ('Cameroon', 'Yaounde'),
 ('Comoros', 'Moroni'),
 ('Colombia', 'Bogota'),
 ('Northern Mariana Islands', 'Saipan'),
 ('Costa Rica', 'San Jose'),
 ('Central African Republic', 'Bangui'),
 ('Cuba', 'Havana'),
 ('Cabo Verde', 'Praia'),
 ('Cyprus', 'Nicosia'),
 ('Denmark', 'Copenhagen'),
 ('Djibouti', 'Djibouti'),
 ('Dominica', 'Roseau'),
 ('Dominican Republic', 'Santo Domingo'),
 ('Ecuador', 'Quito'),
 ('Egypt', 'Cairo'),
 ('Ireland', 'Dublin'),
 ('Equatorial Guinea', 'Malabo'),
 ('Estonia', 'Tallinn'),
 ('Eritrea', 'Asmara'),
 ('El Salvador', 'San Salvador'),
 ('Ethiopia', 'Addis Ababa'),
 ('Czech Republic', 'Prague'),
 ('Finland', 'Helsinki'),
 ('Fiji', 'Suva'),
 ('Falkland Islands (Islas Malvinas)', 'Stanley'),
 ('Micronesia, Federated States of', 'Palikir'),
 ('Faroe Islands', 'Torshavn'),
 ('French Polynesia', 'Papeete'),
 ('France', 'Paris'),
 ('Gambia, The', 'Banjul'),
 ('Gabon', 'Libreville'),
 ('Georgia', 'Tbilisi'),
 ('Ghana', 'Accra'),
 ('Grenada', "Saint George'S"),
 ('Greenland', 'Nuuk'),
 ('Germany', 'Berlin'),
 ('Guam', 'Hagatna'),
 ('Greece', 'Athens'),
 ('Guatemala', 'Guatemala City'),
 ('Guinea', 'Conakry'),
 ('Guyana', 'Georgetown'),
 ('Haiti', 'Port-Au-Prince'),
 ('Honduras', 'Tegucigalpa'),
 ('Croatia', 'Zagreb'),
 ('Hungary', 'Budapest'),
 ('Iceland', 'Reykjavik'),
 ('Indonesia', 'Jakarta'),
 ('Isle of Man', 'Douglas'),
 ('India', 'New Delhi'),
 ('Iran', 'Tehran'),
 ('Israel', 'Jerusalem'),
 ('Italy', 'Rome'),
 ("Cote d'Ivoire", 'Yamoussoukro'),
 ('Iraq', 'Baghdad'),
 ('Japan', 'Tokyo'),
 ('Jamaica', 'Kingston'),
 ('Jordan', 'Amman'),
 ('Kenya', 'Nairobi'),
 ('Kyrgyzstan', 'Bishkek'),
 ('Korea, North', 'Pyongyang'),
 ('Kiribati', 'Tarawa'),
 ('Korea, South', 'Seoul'),
 ('Kuwait', 'Kuwait'),
 ('Kazakhstan', 'Astana'),
 ('Laos', 'Vientiane'),
 ('Lebanon', 'Beirut'),
 ('Latvia', 'Riga'),
 ('Lithuania', 'Vilnius'),
 ('Liberia', 'Monrovia'),
 ('Slovakia', 'Bratislava'),
 ('Liechtenstein', 'Vaduz'),
 ('Lesotho', 'Maseru'),
 ('Luxembourg', 'Luxembourg'),
 ('Libya', 'Tripoli'),
 ('Madagascar', 'Antananarivo'),
 ('Moldova', 'Chisinau'),
 ('Mongolia', 'Ulaanbaatar'),
 ('Malawi', 'Lilongwe'),
 ('Montenegro', 'Podgorica'),
 ('Macedonia', 'Skopje'),
 ('Mali', 'Bamako'),
 ('Morocco', 'Rabat'),
 ('Mauritius', 'Port Louis'),
 ('Mauritania', 'Nouakchott'),
 ('Malta', 'Valletta'),
 ('Oman', 'Muscat'),
 ('Maldives', 'Male'),
 ('Mexico', 'Mexico City'),
 ('Malaysia', 'Kuala Lumpur'),
 ('Mozambique', 'Maputo'),
 ('New Caledonia', 'Noumea'),
 ('Niger', 'Niamey'),
 ('Vanuatu', 'Port-Vila'),
 ('Nigeria', 'Abuja'),
 ('Netherlands', 'Amsterdam'),
 ('Norway', 'Oslo'),
 ('Nepal', 'Kathmandu'),
 ('Suriname', 'Paramaribo'),
 ('Nicaragua', 'Managua'),
 ('New Zealand', 'Wellington'),
 ('South Sudan', 'Juba'),
 ('Paraguay', 'Asuncion'),
 ('Peru', 'Lima'),
 ('Pakistan', 'Islamabad'),
 ('Poland', 'Warsaw'),
 ('Panama', 'Panama City'),
 ('Portugal', 'Lisbon'),
 ('Papua New Guinea', 'Port Moresby'),
 ('Palau', 'Melekeok'),
 ('Guinea-Bissau', 'Bissau'),
 ('Qatar', 'Doha'),
 ('Serbia', 'Belgrade'),
 ('Marshall Islands', 'Majuro'),
 ('Romania', 'Bucharest'),
 ('Philippines', 'Manila'),
 ('Puerto Rico', 'San Juan'),
 ('Russia', 'Moscow'),
 ('Rwanda', 'Kigali'),
 ('Saudi Arabia', 'Riyadh'),
 ('Saint Pierre and Miquelon', 'Saint-Pierre'),
 ('Saint Kitts and Nevis', 'Basseterre'),
 ('Seychelles', 'Victoria'),
 ('South Africa', 'Pretoria'),
 ('Senegal', 'Dakar'),
 ('Saint Helena, Ascension, and Tristan da Cunha', 'Jamestown'),
 ('Slovenia', 'Ljubljana'),
 ('Sierra Leone', 'Freetown'),
 ('Somalia', 'Mogadishu'),
 ('Spain', 'Madrid'),
 ('Saint Lucia', 'Castries'),
 ('Sudan', 'Khartoum'),
 ('Sweden', 'Stockholm'),
 ('Syria', 'Damascus'),
 ('Switzerland', 'Bern'),
 ('Trinidad and Tobago', 'Port-Of-Spain'),
 ('Thailand', 'Bangkok'),
 ('Tajikistan', 'Dushanbe'),
 ('Turks and Caicos Islands', 'Grand Turk'),
 ('Togo', 'Lome'),
 ('Sao Tome and Principe', 'Sao Tome'),
 ('Tunisia', 'Tunis'),
 ('Timor-Leste', 'Dili'),
 ('Turkey', 'Ankara'),
 ('Tuvalu', 'Funafuti'),
 ('Turkmenistan', 'Ashgabat'),
 ('Tanzania', 'Dar Es Salaam'),
 ('Uganda', 'Kampala'),
 ('United Kingdom', 'London'),
 ('Ukraine', 'Kyiv'),
 ('United States', 'Washington, D.C.'),
 ('Burkina Faso', 'Ouagadougou'),
 ('Uruguay', 'Montevideo'),
 ('Uzbekistan', 'Tashkent'),
 ('Saint Vincent and the Grenadines', 'Kingstown'),
 ('Venezuela', 'Caracas'),
 ('British Virgin Islands', 'Road Town'),
 ('Vietnam', 'Hanoi'),
 ('Virgin Islands', 'Charlotte Amalie'),
 ('Namibia', 'Windhoek'),
 ('Wallis and Futuna', 'Mata-Utu'),
 ('Samoa', 'Apia'),
 ('Swaziland', 'Mbabane'),
 ('Yemen', 'Sanaa'),
 ('Zambia', 'Lusaka'),
 ('Zimbabwe', 'Harare')]

As we mentioned earlier, an inner join will not include any rows where there is not a mutual match from both tables. This means there could be information we are not seeing in our query where rows don't match.

We can use some SQL queries to explore this

In [21]:
%%sql
SELECT COUNT(DISTINCT(name)) FROM facts;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[(261,)]

In [22]:
%%sql
SELECT COUNT(DISTINCT(facts_id)) FROM cities;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[(210,)]

By running these two queries, we can see that there are some countries in the `facts` table that don't have corresponding `cities` in the cities table, which indicates we may have some incomplete data.

### Left joins

A left join includes all the rows that an inner join will select, plus any rows from the first (or left) table that don't have a match in the second table. 

Let's look at an example by replacing INNER JOIN with LEFT JOIN from the first query we wrote,

In [25]:
%%sql
SELECT * FROM facts
LEFT JOIN cities ON cities.facts_id = facts.id

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[(1, 'af', 'Afghanistan', 652230, 652230, 0, 32564342, 2.32, 38.57, 13.89, 1.51, 6, 'Kabul', 3097000, 1, '1'),
 (2, 'al', 'Albania', 28748, 27398, 1350, 3029278, 0.3, 12.92, 6.58, 3.3, 10, 'Tirana', 419000, 1, '2'),
 (3, 'ag', 'Algeria', 2381741, 2381741, 0, 39542166, 1.84, 23.67, 4.31, 0.92, 7, 'Algiers', 2916000, 1, '3'),
 (3, 'ag', 'Algeria', 2381741, 2381741, 0, 39542166, 1.84, 23.67, 4.31, 0.92, 8, 'Oran', 783000, 0, '3'),
 (4, 'an', 'Andorra', 468, 468, 0, 85580, 0.12, 8.13, 6.96, 0.0, 12, 'Andorra La Vella', 23000, 1, '4'),
 (5, 'ao', 'Angola', 1246700, 1246700, 0, 19625353, 2.78, 38.78, 11.49, 0.46, 13, 'Luanda', 5068000, 1, '5'),
 (5, 'ao', 'Angola', 1246700, 1246700, 0, 19625353, 2.78, 38.78, 11.49, 0.46, 14, 'Huambo', 1098000, 0, '5'),
 (6, 'ac', 'Antigua and Barbuda', 442, 442, 0, 92436, 1.24, 15.85, 5.69, 2.21, 2, "Saint John'S", 27000, 1, '6'),
 (7, 'ar', 'Argentina', 2780400, 2736690, 43710, 43431886, 0.93, 16.64, 7.33, 0.0, 16, 'Buenos Aires', 13528000, 1, '7'),
 (7, 'ar', 'Argentina', 2780400, 2736690, 43710, 43431886, 0.93, 16.64, 7.33, 0.0, 17, 'Cordoba', 1556000, 0, '7'),
 (7, 'ar', 'Argentina', 2780400, 2736690, 43710, 43431886, 0.93, 16.64, 7.33, 0.0, 18, 'Rosario', 1283000, 0, '7'),
 (7, 'ar', 'Argentina', 2780400, 2736690, 43710, 43431886, 0.93, 16.64, 7.33, 0.0, 19, 'Mendoza', 957000, 0, '7'),
 (7, 'ar', 'Argentina', 2780400, 2736690, 43710, 43431886, 0.93, 16.64, 7.33, 0.0, 20, 'San Miguel de Tucuman', 868000, 0, '7'),
 (7, 'ar', 'Argentina', 2780400, 2736690, 43710, 43431886, 0.93, 16.64, 7.33, 0.0, 21, 'La Plata', 759000, 0, '7'),
 (8, 'am', 'Armenia', 29743, 28203, 1540, 3056382, 0.15, 13.61, 9.34, 5.8, 11, 'Yerevan', 1116000, 1, '8'),
 (9, 'as', 'Australia', 7741220, 7682300, 58920, 22751014, 1.07, 12.15, 7.14, 5.65, 22, 'Sydney', 4543000, 0, '9'),
 (9, 'as', 'Australia', 7741220, 7682300, 58920, 22751014, 1.07, 12.15, 7.14, 5.65, 23, 'Melbourne', 3961000, 0, '9'),
 (9, 'as', 'Australia', 7741220, 7682300, 58920, 22751014, 1.07, 12.15, 7.14, 5.65, 24, 'Brisbane', 2039000, 0, '9'),
 (9, 'as', 'Australia', 7741220, 7682300, 58920, 22751014, 1.07, 12.15, 7.14, 5.65, 25, 'Perth', 1649000, 0, '9'),
 (9, 'as', 'Australia', 7741220, 7682300, 58920, 22751014, 1.07, 12.15, 7.14, 5.65, 26, 'Adelaide', 1198000, 0, '9'),
 (9, 'as', 'Australia', 7741220, 7682300, 58920, 22751014, 1.07, 12.15, 7.14, 5.65, 27, 'Canberra', 399000, 1, '9'),
 (10, 'au', 'Austria', 83871, 82445, 1426, 8665550, 0.55, 9.41, 9.42, 5.56, 28, 'Vienna', 172000, 1, '10'),
 (11, 'aj', 'Azerbaijan', 86600, 82629, 3971, 9780780, 0.96, 16.64, 7.07, 0.0, 9, 'Baku', 2123000, 1, '11'),
 (12, 'bf', 'Bahamas, The', 13880, 10010, 3870, 324597, 0.85, 15.5, 7.05, 0.0, 36, 'Nassau', 254000, 1, '12'),
 (13, 'ba', 'Bahrain', 760, 760, 0, 1346613, 2.41, 13.66, 2.69, 13.09, 30, 'Manama', 262000, 1, '13'),
 (14, 'bg', 'Bangladesh', 148460, 130170, 18290, 168957745, 1.6, 21.14, 5.61, 0.46, 37, 'Dhaka', 15391000, 1, '14'),
 (14, 'bg', 'Bangladesh', 148460, 130170, 18290, 168957745, 1.6, 21.14, 5.61, 0.46, 38, 'Chittagong', 5239000, 0, '14'),
 (14, 'bg', 'Bangladesh', 148460, 130170, 18290, 168957745, 1.6, 21.14, 5.61, 0.46, 39, 'Khulna', 1781000, 0, '14'),
 (14, 'bg', 'Bangladesh', 148460, 130170, 18290, 168957745, 1.6, 21.14, 5.61, 0.46, 40, 'Rajshahi', 932000, 0, '14'),
 (15, 'bb', 'Barbados', 430, 430, 0, 290604, 0.31, 11.87, 8.44, 0.3, 31, 'Bridgetown', 122000, 1, '15'),
 (16, 'bo', 'Belarus', 207600, 202900, 4700, 9589689, 0.2, 10.7, 13.36, 0.7, 51, 'Minsk', 1861000, 1, '16'),
 (17, 'be', 'Belgium', 30528, 30278, 250, 11323973, 0.76, 11.41, 9.63, 5.87, 34, 'Brussels', 1949000, 1, '17'),
 (17, 'be', 'Belgium', 30528, 30278, 250, 11323973, 0.76, 11.41, 9.63, 5.87, 35, 'Antwerp', 959000, 0, '17'),
 (18, 'bh', 'Belize', 22966, 22806, 160, 347369, 1.87, 24.68, 5.97, 0.0, 41, 'Belmopan', 14000, 1, '18'),
 (19, 'bn', 'Benin', 112622, 110622, 2000, 10448647, 2.78, 36.02, 8.21, 0.0, 49, 'COTONOU (seat of government)', 924000, 0, '19'),
 (19, 'bn', 'Benin', 112622, 110622, 2000, 10448647, 2.78, 36.02, 8.21, 0.0, 50, 'Porto-Novo', 314000, 1, '19'),
 (20, 'bt', 'Bhutan', 38394, 38394, 0, 741919, 1.11, 17.78, 6.69, 0.0, 59, 'Thimphu', 99000, 1, '20'),
 (21, 'bl', 'Bolivia', 1098581, 1083301, 15280, 10800882, 1.56, 22.76, 6.52, 0.62, 43, 'Santa Cruz', 1719000, 0, '21'),
 (21, 'bl', 'Bolivia', 1098581, 1083301, 15280, 10800882, 1.56, 22.76, 6.52, 0.62, 44, 'La Paz', 1715000, 1, '21'),
 (21, 'bl', 'Bolivia', 1098581, 1083301, 15280, 10800882, 1.56, 22.76, 6.52, 0.62, 45, 'Sucre (constitutional capital)', 307000, 0, '21'),
 (22, 'bk', 'Bosnia and Herzegovina', 51197, 51187, 10, 3867055, 0.13, 8.87, 9.75, 0.38, 42, 'Sarajevo', 389000, 1, '22'),
 (23, 'bc', 'Botswana', 581730, 566730, 15000, 2182719, 1.21, 20.96, 13.39, 4.56, 32, 'Gaborone', 202000, 1, '23'),
 (24, 'br', 'Brazil', 8515770, 8358140, 157630, 204259812, 0.77, 14.46, 6.58, 0.14, 53, 'Sao Paulo', 19924000, 0, '24'),
 (24, 'br', 'Brazil', 8515770, 8358140, 157630, 204259812, 0.77, 14.46, 6.58, 0.14, 54, 'Rio de Janeiro', 1196000, 0, '24'),
 (24, 'br', 'Brazil', 8515770, 8358140, 157630, 204259812, 0.77, 14.46, 6.58, 0.14, 55, 'Belo Horizonte', 5487000, 0, '24'),
 (24, 'br', 'Brazil', 8515770, 8358140, 157630, 204259812, 0.77, 14.46, 6.58, 0.14, 56, 'Porto Alegre', 3933000, 0, '24'),
 (24, 'br', 'Brazil', 8515770, 8358140, 157630, 204259812, 0.77, 14.46, 6.58, 0.14, 57, 'Recife', 3733000, 0, '24'),
 (24, 'br', 'Brazil', 8515770, 8358140, 157630, 204259812, 0.77, 14.46, 6.58, 0.14, 58, 'Brasilia', 3813000, 1, '24'),
 (25, 'bx', 'Brunei', 5765, 5265, 500, 429646, 1.62, 17.32, 3.52, 2.43, 61, 'Bandar Seri Begawan', 241000, 1, '25'),
 (26, 'bu', 'Bulgaria', 110879, 108489, 2390, 7186893, 0.58, 8.92, 14.44, 0.29, 60, 'Sofia', 1174000, 1, '26'),
 (27, 'uv', 'Burkina Faso', 274200, 273800, 400, 18931686, 3.03, 42.03, 11.72, 0.0, 373, 'Ouagadougou', 2053000, 1, '27'),
 (28, 'bm', 'Burma', 676578, 653508, 23070, 56320206, 1.01, 18.39, 7.96, 0.28, 46, 'Rangoon', 4457000, 1, '28'),
 (28, 'bm', 'Burma', 676578, 653508, 23070, 56320206, 1.01, 18.39, 7.96, 0.28, 47, 'Mandalay', 1063000, 0, '28'),
 (28, 'bm', 'Burma', 676578, 653508, 23070, 56320206, 1.01, 18.39, 7.96, 0.28, 48, 'Nay Pyi Taw', 106000, 0, '28'),
 (29, 'by', 'Burundi', 27830, 25680, 2150, 10742276, 3.28, 42.01, 9.27, 0.0, 62, 'Bujumbura', 605000, 1, '29'),
 (30, 'cb', 'Cambodia', 181035, 176515, 4520, 15708756, 1.58, 23.83, 7.68, 0.32, 69, 'Phnom Penh', 155000, 1, '30'),
 (31, 'cm', 'Cameroon', 475440, 472710, 2730, 23739218, 2.59, 36.17, 10.11, 0.15, 90, 'Douala', 2449000, 0, '31'),
 (31, 'cm', 'Cameroon', 475440, 472710, 2730, 23739218, 2.59, 36.17, 10.11, 0.15, 91, 'Yaounde', 2432000, 1, '31'),
 (32, 'ca', 'Canada', 9984670, 9093507, 891163, 35099836, 0.75, 10.28, 8.42, 5.66, 63, 'Toronto', 5573000, 0, '32'),
 (32, 'ca', 'Canada', 9984670, 9093507, 891163, 35099836, 0.75, 10.28, 8.42, 5.66, 64, 'Montreal', 3856000, 0, '32'),
 (32, 'ca', 'Canada', 9984670, 9093507, 891163, 35099836, 0.75, 10.28, 8.42, 5.66, 65, 'Vancouver', 2267000, 0, '32'),
 (32, 'ca', 'Canada', 9984670, 9093507, 891163, 35099836, 0.75, 10.28, 8.42, 5.66, 66, 'Calgary', 1216000, 0, '32'),
 (32, 'ca', 'Canada', 9984670, 9093507, 891163, 35099836, 0.75, 10.28, 8.42, 5.66, 67, 'Ottawa', 1208000, 1, '32'),
 (32, 'ca', 'Canada', 9984670, 9093507, 891163, 35099836, 0.75, 10.28, 8.42, 5.66, 68, 'Edmonton', 1142000, 0, '32'),
 (33, 'cv', 'Cabo Verde', 4033, 4033, 0, 545993, 1.36, 20.33, 6.11, 0.63, 103, 'Praia', 132000, 1, '33'),
 (34, 'ct', 'Central African Republic', 622984, 622984, 0, 5391539, 2.13, 35.08, 13.8, 0.0, 101, 'Bangui', 740000, 1, '34'),
 (35, 'cd', 'Chad', None, 1259200, 24800, 11631456, 1.89, 36.6, 14.28, 3.45, 70, "N'Djamena", 1079000, 1, '35'),
 (36, 'ci', 'Chile', 756102, 743812, 12290, 17508260, 0.82, 13.83, 6.0, 0.34, 86, 'Santiago', 6034000, 1, '36'),
 (36, 'ci', 'Chile', 756102, 743812, 12290, 17508260, 0.82, 13.83, 6.0, 0.34, 87, 'Valparaiso', 883000, 0, '36'),
 (36, 'ci', 'Chile', 756102, 743812, 12290, 17508260, 0.82, 13.83, 6.0, 0.34, 88, 'Concepcion', 770000, 0, '36'),
 (37, 'ch', 'China', 9596960, 9326410, 270550, 1367485388, 0.45, 12.49, 7.53, 0.44, 80, 'Shanghai', 20208000, 0, '37'),
 (37, 'ch', 'China', 9596960, 9326410, 270550, 1367485388, 0.45, 12.49, 7.53, 0.44, 81, 'Beijing', 15594000, 1, '37'),
 (37, 'ch', 'China', 9596960, 9326410, 270550, 1367485388, 0.45, 12.49, 7.53, 0.44, 82, 'Guangzhou', 10849000, 0, '37'),
 (37, 'ch', 'China', 9596960, 9326410, 270550, 1367485388, 0.45, 12.49, 7.53, 0.44, 83, 'Shenzhen', 1063000, 0, '37'),
 (37, 'ch', 'China', 9596960, 9326410, 270550, 1367485388, 0.45, 12.49, 7.53, 0.44, 84, 'Chongqing', 9977000, 0, '37'),
 (37, 'ch', 'China', 9596960, 9326410, 270550, 1367485388, 0.45, 12.49, 7.53, 0.44, 85, 'Wuhan', 9158000, 0, '37'),
 (38, 'co', 'Colombia', 1138910, 1038700, 100210, 46736728, 1.04, 16.47, 5.4, 0.64, 93, 'Bogota', 8743000, 1, '38'),
 (38, 'co', 'Colombia', 1138910, 1038700, 100210, 46736728, 1.04, 16.47, 5.4, 0.64, 94, 'Medellin', 3694000, 0, '38'),
 (38, 'co', 'Colombia', 1138910, 1038700, 100210, 46736728, 1.04, 16.47, 5.4, 0.64, 95, 'Cali', 2453000, 0, '38'),
 (38, 'co', 'Colombia', 1138910, 1038700, 100210, 46736728, 1.04, 16.47, 5.4, 0.64, 96, 'Barranquilla', 19000, 0, '38'),
 (38, 'co', 'Colombia', 1138910, 1038700, 100210, 46736728, 1.04, 16.47, 5.4, 0.64, 97, 'Bucaramanga', 112000, 0, '38'),
 (38, 'co', 'Colombia', 1138910, 1038700, 100210, 46736728, 1.04, 16.47, 5.4, 0.64, 98, 'Cartagena', 988000, 0, '38'),
 (39, 'cn', 'Comoros', 2235, 2235, 0, 780971, 1.77, 27.84, 7.57, 2.53, 92, 'Moroni', 54000, 1, '39'),
 (40, 'cg', 'Congo, Democratic Republic of the', 2344858, 2267048, 77810, 79375136, 2.45, 34.88, 10.07, 0.27, 75, 'Kinshasa', 8798000, 1, '40'),
 (40, 'cg', 'Congo, Democratic Republic of the', 2344858, 2267048, 77810, 79375136, 2.45, 34.88, 10.07, 0.27, 76, 'Lubumbashi', 1556000, 0, '40'),
 (40, 'cg', 'Congo, Democratic Republic of the', 2344858, 2267048, 77810, 79375136, 2.45, 34.88, 10.07, 0.27, 77, 'Mbuji-Mayi', 1504000, 0, '40'),
 (40, 'cg', 'Congo, Democratic Republic of the', 2344858, 2267048, 77810, 79375136, 2.45, 34.88, 10.07, 0.27, 78, 'Kananga', 888000, 0, '40'),
 (40, 'cg', 'Congo, Democratic Republic of the', 2344858, 2267048, 77810, 79375136, 2.45, 34.88, 10.07, 0.27, 79, 'Kisangani', 820000, 0, '40'),
 (41, 'cf', 'Congo, Republic of the', 342000, 341500, 500, 4755097, 2.0, 35.85, 10.0, 5.9, 73, 'Brazzaville', 1611000, 1, '41'),
 (41, 'cf', 'Congo, Republic of the', 342000, 341500, 500, 4755097, 2.0, 35.85, 10.0, 5.9, 74, 'Pointe-Noire', 834000, 0, '41'),
 (42, 'cs', 'Costa Rica', 51100, 51060, 40, 4814144, 1.22, 15.91, 4.55, 0.83, 100, 'San Jose', 1515000, 1, '42'),
 (43, 'iv', "Cote d'Ivoire", 322463, 318003, 4460, 23295302, 1.91, 28.67, 9.55, 0.0, 182, 'ABIDJAN (seat of government)', 4288000, 0, '43'),
 (43, 'iv', "Cote d'Ivoire", 322463, 318003, 4460, 23295302, 1.91, 28.67, 9.55, 0.0, 183, 'Yamoussoukro', 966000, 1, '43'),
 (44, 'hr', 'Croatia', 56594, 55974, 620, 4464844, 0.13, 9.45, 12.18, 1.39, 151, 'Zagreb', 686000, 1, '44'),
 (45, 'cu', 'Cuba', 110860, 109820, 1040, 11031433, 0.15, 9.9, 7.72, 3.66, 102, 'Havana', 2116000, 1, '45'),
 (46, 'cy', 'Cyprus', 9251, 9241, 10, 1189197, 1.43, 11.41, 6.62, 9.48, 104, 'Nicosia', 253000, 1, '46'),
 (47, 'ez', 'Czech Republic', 78867, 77247, 1620, 10644842, 0.16, 9.63, 10.34, 2.33, 119, 'Prague', 1276000, 1, '47'),
 (48, 'da', 'Denmark', 43094, 42434, 660, 5581503, 0.22, 10.27, 10.25, 2.2, 105, 'Copenhagen', 1206000, 1, '48'),
 (49, 'dj', 'Djibouti', 23200, 23180, 20, 828324, 2.2, 23.65, 7.73, 6.06, 106, 'Djibouti', 496000, 1, '49'),
 (50, 'do', 'Dominica', 751, 751, 0, 73607, 0.21, 15.41, 7.91, 5.38, 107, 'Roseau', 14000, 1, '50'),
 (51, 'dr', 'Dominican Republic', 48670, 48320, 350, 10478756, 1.23, 18.73, 4.55, 1.91, 108, 'Santo Domingo', 2191000, 1, '51'),
 (52, 'ec', 'Ecuador', 283561, 276841, 6720, 15868396, 1.35, 18.51, 5.06, 0.0, 109, 'Guayaquil', 2287000, 0, '52'),
 (52, 'ec', 'Ecuador', 283561, 276841, 6720, 15868396, 1.35, 18.51, 5.06, 0.0, 110, 'Quito', 1622000, 1, '52'),
 (53, 'eg', 'Egypt', 1001450, 995450, 6000, 88487396, 1.79, 22.9, 4.77, 0.19, 111, 'Cairo', 11169000, 1, '53'),
 (53, 'eg', 'Egypt', 1001450, 995450, 6000, 88487396, 1.79, 22.9, 4.77, 0.19, 112, 'Alexandria', 4494000, 0, '53'),
 (54, 'es', 'El Salvador', 21041, 20721, 320, 6141350, 0.25, 16.46, 5.69, 8.28, 117, 'San Salvador', 1605000, 1, '54'),
 (55, 'ek', 'Equatorial Guinea', 28051, 28051, 0, 740743, 2.51, 33.31, 8.19, 0.0, 114, 'Malabo', 137000, 1, '55'),
 (56, 'er', 'Eritrea', 117600, 101000, 16600, 6527689, 2.25, 30.0, 7.52, 0.0, 116, 'Asmara', 712000, 1, '56'),
 (57, 'en', 'Estonia', 45228, 42388, 2840, 1265420, 0.55, 10.51, 12.4, 3.6, 115, 'Tallinn', 400000, 1, '57'),
 (58, 'et', 'Ethiopia', 1104300, None, 104300, 99465819, 2.89, 37.27, 8.19, 0.22, 118, 'Addis Ababa', 2979000, 1, '58'),
 (59, 'fj', 'Fiji', 18274, 18274, 0, 909389, 0.67, 19.43, 6.04, 6.75, 121, 'Suva', 177000, 1, '59'),
 (60, 'fi', 'Finland', 338145, 303815, 34330, 5476922, 0.4, 10.72, 9.83, 3.1, 120, 'Helsinki', 1134000, 1, '60'),
 (61, 'fr', 'France', 643801, 640427, 3374, 66553766, 0.43, 12.38, 9.16, 1.09, 126, 'Paris', 1062000, 1, '61'),
 (61, 'fr', 'France', 643801, 640427, 3374, 66553766, 0.43, 12.38, 9.16, 1.09, 127, 'Marseille-Aix-en-Provence', 14890100, 0, '61'),
 (61, 'fr', 'France', 643801, 640427, 3374, 66553766, 0.43, 12.38, 9.16, 1.09, 128, 'Lyon', 1488000, 0, '61'),
 (61, 'fr', 'France', 643801, 640427, 3374, 66553766, 0.43, 12.38, 9.16, 1.09, 129, 'Lille', 1042000, 0, '61'),
 (61, 'fr', 'France', 643801, 640427, 3374, 66553766, 0.43, 12.38, 9.16, 1.09, 130, 'Nice-Cannes', 991000, 0, '61'),
 (61, 'fr', 'France', 643801, 640427, 3374, 66553766, 0.43, 12.38, 9.16, 1.09, 131, 'Toulouse', 933000, 0, '61'),
 (62, 'gb', 'Gabon', 267667, 257667, 10000, 1705336, 1.93, 34.49, 13.12, 2.03, 133, 'Libreville', 686000, 1, '62'),
 (63, 'ga', 'Gambia, The', 11300, 10120, 1180, 1967709, 2.16, 30.86, 7.15, 2.12, 132, 'Banjul', 506000, 1, '63'),
 (64, 'gg', 'Georgia', 69700, 69700, 0, 4931226, 0.08, 12.74, 10.82, 2.7, 134, 'Tbilisi', 1121000, 1, '64'),
 (65, 'gm', 'Germany', 357022, 348672, 8350, 80854408, 0.17, 8.47, 11.42, 1.24, 139, 'Berlin', 3462000, 1, '65'),
 (65, 'gm', 'Germany', 357022, 348672, 8350, 80854408, 0.17, 8.47, 11.42, 1.24, 140, 'Hamburg', 1796000, 0, '65'),
 (65, 'gm', 'Germany', 357022, 348672, 8350, 80854408, 0.17, 8.47, 11.42, 1.24, 141, 'Munich', 1364000, 0, '65'),
 (65, 'gm', 'Germany', 357022, 348672, 8350, 80854408, 0.17, 8.47, 11.42, 1.24, 142, 'Cologne', 1006000, 0, '65'),
 (66, 'gh', 'Ghana', 238533, 227533, 11000, 26327649, 2.18, 31.09, 7.22, 2.02, 135, 'Accra', 2573000, 1, '66'),
 (66, 'gh', 'Ghana', 238533, 227533, 11000, 26327649, 2.18, 31.09, 7.22, 2.02, 136, 'Kumasi', 2019000, 0, '66'),
 (67, 'gr', 'Greece', 131957, 130647, 1310, 10775643, 0.01, 8.66, 11.09, 2.32, 144, 'Athens', 3414000, 1, '67'),
 (67, 'gr', 'Greece', 131957, 130647, 1310, 10775643, 0.01, 8.66, 11.09, 2.32, 145, 'Thessaloniki', 883000, 0, '67'),
 (68, 'gj', 'Grenada', 344, 344, 0, 110694, 0.48, 16.03, 8.08, 3.13, 137, "Saint George'S", 41000, 1, '68'),
 (69, 'gt', 'Guatemala', 108889, 107159, 1730, 14918999, 1.82, 24.89, 4.77, 1.97, 146, 'Guatemala City', 1168000, 1, '69'),
 (70, 'gv', 'Guinea', 245857, 245717, 140, 11780162, 2.63, 35.74, 9.46, 0.0, 147, 'Conakry', 1786000, 1, '70'),
 (71, 'pu', 'Guinea-Bissau', 36125, 28120, 8005, 1726170, 1.91, 33.38, 14.33, 0.0, 286, 'Bissau', 423000, 1, '71'),
 (72, 'gy', 'Guyana', 214969, 196849, 18120, 735222, 0.02, 15.59, 7.32, 8.06, 148, 'Georgetown', 127000, 1, '72'),
 (73, 'ha', 'Haiti', 27750, 27560, 190, 10110019, 1.17, 22.31, 7.83, 2.76, 149, 'Port-Au-Prince', 2207000, 1, '73'),
 (74, 'ho', 'Honduras', 112090, 111890, 200, 8746673, 1.68, 23.14, 5.17, 1.16, 150, 'Tegucigalpa', 1088000, 1, '74'),
 (75, 'hu', 'Hungary', 93028, 89608, 3420, 9897541, 0.22, 9.16, 12.73, 1.33, 152, 'Budapest', 1737000, 1, '75'),
 (76, 'ic', 'Iceland', 103000, 100250, 2750, 331918, 1.21, 13.91, 6.28, 4.43, 153, 'Reykjavik', 206000, 1, '76'),
 (77, 'in', 'India', 3287263, 2973193, 314070, 1251695584, 1.22, 19.55, 7.32, 0.04, 161, 'New Delhi', 22654000, 1, '77'),
 (77, 'in', 'India', 3287263, 2973193, 314070, 1251695584, 1.22, 19.55, 7.32, 0.04, 162, 'Mumbai', 19744000, 0, '77'),
 (77, 'in', 'India', 3287263, 2973193, 314070, 1251695584, 1.22, 19.55, 7.32, 0.04, 163, 'Kolkata', 14402000, 0, '77'),
 (77, 'in', 'India', 3287263, 2973193, 314070, 1251695584, 1.22, 19.55, 7.32, 0.04, 164, 'Chennai', 8784000, 0, '77'),
 (77, 'in', 'India', 3287263, 2973193, 314070, 1251695584, 1.22, 19.55, 7.32, 0.04, 165, 'Bangalore', 8614000, 0, '77'),
 (77, 'in', 'India', 3287263, 2973193, 314070, 1251695584, 1.22, 19.55, 7.32, 0.04, 166, 'Hyderabad', 7837000, 0, '77'),
 (78, 'id', 'Indonesia', 1904569, 1811569, 93000, 255993674, 0.92, 16.72, 6.37, 1.16, 154, 'Jakarta', 9769000, 1, '78'),
 (78, 'id', 'Indonesia', 1904569, 1811569, 93000, 255993674, 0.92, 16.72, 6.37, 1.16, 155, 'Surabaya', 2787000, 0, '78'),
 (78, 'id', 'Indonesia', 1904569, 1811569, 93000, 255993674, 0.92, 16.72, 6.37, 1.16, 156, 'Bandung', 2429000, 0, '78'),
 (78, 'id', 'Indonesia', 1904569, 1811569, 93000, 255993674, 0.92, 16.72, 6.37, 1.16, 157, 'Medan', 2118000, 0, '78'),
 (78, 'id', 'Indonesia', 1904569, 1811569, 93000, 255993674, 0.92, 16.72, 6.37, 1.16, 158, 'Semarang', 1573000, 0, '78'),
 (78, 'id', 'Indonesia', 1904569, 1811569, 93000, 255993674, 0.92, 16.72, 6.37, 1.16, 159, 'Palembang', 1455000, 0, '78'),
 (79, 'ir', 'Iran', 1648195, 1531595, 116600, 81824270, 1.2, 17.99, 5.94, 0.07, 167, 'Tehran', 7304000, 1, '79'),
 (79, 'ir', 'Iran', 1648195, 1531595, 116600, 81824270, 1.2, 17.99, 5.94, 0.07, 168, 'Mashhad', 2713000, 0, '79'),
 (79, 'ir', 'Iran', 1648195, 1531595, 116600, 81824270, 1.2, 17.99, 5.94, 0.07, 169, 'Esfahan', 1781000, 0, '79'),
 (79, 'ir', 'Iran', 1648195, 1531595, 116600, 81824270, 1.2, 17.99, 5.94, 0.07, 170, 'Karaj', 1635000, 0, '79'),
 (79, 'ir', 'Iran', 1648195, 1531595, 116600, 81824270, 1.2, 17.99, 5.94, 0.07, 171, 'Tabriz', 1509000, 0, '79'),
 (79, 'ir', 'Iran', 1648195, 1531595, 116600, 81824270, 1.2, 17.99, 5.94, 0.07, 172, 'Shiraz', 1321000, 0, '79'),
 (80, 'iz', 'Iraq', 438317, 437367, 950, 37056169, 2.93, 31.45, 3.77, 1.62, 184, 'Baghdad', 6036000, 1, '80'),
 (80, 'iz', 'Iraq', 438317, 437367, 950, 37056169, 2.93, 31.45, 3.77, 1.62, 185, 'Mosul', 1494000, 0, '80'),
 (80, 'iz', 'Iraq', 438317, 437367, 950, 37056169, 2.93, 31.45, 3.77, 1.62, 186, 'Erbil', 1039000, 0, '80'),
 (80, 'iz', 'Iraq', 438317, 437367, 950, 37056169, 2.93, 31.45, 3.77, 1.62, 187, 'Basra', 942000, 0, '80'),
 (80, 'iz', 'Iraq', 438317, 437367, 950, 37056169, 2.93, 31.45, 3.77, 1.62, 188, 'As Sulaymaniyah', 867000, 0, '80'),
 (80, 'iz', 'Iraq', 438317, 437367, 950, 37056169, 2.93, 31.45, 3.77, 1.62, 189, 'Najaf', 779000, 0, '80'),
 (81, 'ei', 'Ireland', 70273, 68883, 1390, 4892305, 1.25, 14.84, 6.48, 4.09, 113, 'Dublin', 1121000, 1, '81'),
 (82, 'is', 'Israel', 20770, 20330, 440, 8049314, 1.56, 18.48, 5.15, 2.24, 173, 'Tel Aviv-Yafo', 3381000, 0, '82'),
 (82, 'is', 'Israel', 20770, 20330, 440, 8049314, 1.56, 18.48, 5.15, 2.24, 174, 'Haifa', 1054000, 0, '82'),
 (82, 'is', 'Israel', 20770, 20330, 440, 8049314, 1.56, 18.48, 5.15, 2.24, 175, 'Jerusalem', 791000, 1, '82'),
 (83, 'it', 'Italy', 301340, 294140, 7200, 61855120, 0.27, 8.74, 10.19, 4.1, 176, 'Rome', 3298000, 1, '83'),
 (83, 'it', 'Italy', 301340, 294140, 7200, 61855120, 0.27, 8.74, 10.19, 4.1, 177, 'Milan', 2909000, 0, '83'),
 (83, 'it', 'Italy', 301340, 294140, 7200, 61855120, 0.27, 8.74, 10.19, 4.1, 178, 'Naples', 2373000, 0, '83'),
 (83, 'it', 'Italy', 301340, 294140, 7200, 61855120, 0.27, 8.74, 10.19, 4.1, 179, 'Turin', 1613000, 0, '83'),
 (83, 'it', 'Italy', 301340, 294140, 7200, 61855120, 0.27, 8.74, 10.19, 4.1, 180, 'Palermo', 915000, 0, '83'),

Here we can see that for the rows where `facts.id` doesn't match any values in `cities.facts_id (237, 238, 240, and 244)`, the rows are still included in the results. When this happens, all of the columns from the `cities` table are populated with `null` values.

We can use these null values to filter our results to just the countries that don't exist in `cities` with a `WHERE` clause. When making a comparison to null in SQL, we use the `IS` keyword, rather than the = sign. If we want to select rows where a column is null we can write:

WHERE column_name IS NULL

If we want to select rows where a column name isn't null, we use:

WHERE column_name IS NOT NULL

Let's use a left join to explore the countries that don't exist in the cities table.

Write a query that returns the countries that don't exist in cities:
- Your query should return two columns:
    - The country names, with the alias country.
    - The country population.
- Use a LEFT JOIN to join cities to facts.
- Include only the countries from facts that don't have a corresponding value in cities.

In [26]:
%%sql
SELECT f.name country, f.population
FROM facts f
LEFT JOIN cities c ON c.facts_id = f.id
WHERE c.name IS NULL;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[('Kosovo', 1870981),
 ('Monaco', 30535),
 ('Nauru', 9540),
 ('San Marino', 33020),
 ('Singapore', 5674472),
 ('Holy See (Vatican City)', 842),
 ('Taiwan', 23415126),
 ('European Union', 513949445),
 ('Ashmore and Cartier Islands', None),
 ('Christmas Island', 1530),
 ('Cocos (Keeling) Islands', 596),
 ('Coral Sea Islands', None),
 ('Heard Island and McDonald Islands', None),
 ('Norfolk Island', 2210),
 ('Hong Kong', 7141106),
 ('Macau', 592731),
 ('Clipperton Island', None),
 ('French Southern and Antarctic Lands', None),
 ('Saint Barthelemy', 7237),
 ('Saint Martin', 31754),
 ('Curacao', 148406),
 ('Sint Maarten', 39689),
 ('Cook Islands', 9838),
 ('Niue', 1190),
 ('Tokelau', 1337),
 ('Bouvet Island', None),
 ('Jan Mayen', None),
 ('Svalbard', 1872),
 ('Akrotiri', 15700),
 ('British Indian Ocean Territory', None),
 ('Dhekelia', 15700),
 ('Gibraltar', 29258),
 ('Guernsey', 66080),
 ('Jersey', 97294),
 ('Montserrat', 5241),
 ('Pitcairn Islands', 48),
 ('South Georgia and South Sandwich Islands', None),
 ('Navassa Island', None),
 ('Wake Island', None),
 ('United States Pacific Island Wildlife Refuges', None),
 ('Antarctica', 0),
 ('Gaza Strip', 1869055),
 ('Paracel Islands', None),
 ('Spratly Islands', None),
 ('West Bank', 2785366),
 ('Arctic Ocean', None),
 ('Atlantic Ocean', None),
 ('Indian Ocean', None),
 ('Pacific Ocean', None),
 ('Southern Ocean', None),
 ('World', 7256490011)]

Looking through the results of the query we wrote in the previous screen, we can see a number of different reasons that countries don't have corresponding values in cities:

- Countries with small populations and/or no major urban areas (which are defined as having populations of over 750,000), eg San Marino, Kosovo, and Nauru.
- City-states, such as Monaco and Singapore.
- Territories that are not themselves countries, such as Hong Kong, Gibraltar, and the Cook Islands.
- Regions & Oceans that aren't countries, such as the European Union and the Pacific Ocean.
- Genuine cases of missing data, such as Taiwan.

It's important whenever you use inner joins to be mindful that you might be excluding important data, especially if you are joining based on columns that aren't linked in the database schema.

### Right Joins

There are two less-common join types SQLite does not support that you should be aware of. The first is a `right join`. A right join, as the name indicates, is exactly the opposite of a left join. While the left join includes all rows in the table before the JOIN clause, the right join includes all rows in the new table in the JOIN clause. 

The following two queries, one using a left join and one using a right join, produce identical results.

In [27]:
%%sql
SELECT f.name country, c.name city
FROM facts f
LEFT JOIN cities c ON c.facts_id = f.id
LIMIT 5;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[('Afghanistan', 'Kabul'),
 ('Albania', 'Tirana'),
 ('Algeria', 'Algiers'),
 ('Algeria', 'Oran'),
 ('Andorra', 'Andorra La Vella')]

In [28]:
%%sql
SELECT COUNT(DISTINCT(facts_id)) FROM cities;
SELECT f.name country, c.name city
FROM cities c
RIGHT JOIN facts f ON f.id = c.facts_id
LIMIT 5;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.
(sqlite3.OperationalError) RIGHT and FULL OUTER JOINs are not currently supported
[SQL: SELECT f.name country, c.name city
FROM cities c
RIGHT JOIN facts f ON f.id = c.facts_id
LIMIT 5;]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

The main reason a `right join` would be used is when you are joining more than two tables. In these cases, using a right join is preferable because it can avoid restructuring your whole query to join one table. Outside of this, right joins are used reasonably rarely, so for simple joins it's better to use a left join than a right as it will be easier for your query to be read and understood by others.

### Full Outer Joins

The other join type not supported by SQLite is a `full outer join`. A full outer join will include all rows from the tables on both sides of the join.

Like right joins, full outer joins are reasonably uncommon, and similar results can be achieved using a union clause (which we will teach in the next mission). The standard SQL syntax for a full outer join is:

In [29]:
%%sql
SELECT f.name country, c.name city
FROM cities c
FULL OUTER JOIN facts f ON f.id = c.facts_id
LIMIT 5;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
(sqlite3.OperationalError) RIGHT and FULL OUTER JOINs are not currently supported
[SQL: SELECT f.name country, c.name city
FROM cities c
FULL OUTER JOIN facts f ON f.id = c.facts_id
LIMIT 5;]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

When joining `cities` and `facts` with a full outer join, the result will be the same as our left and right joins above, because there are no values in `cities.facts_id` that don't exist in `facts.id`.

### Finding the Most Populous Capital Cities

Previously, we've used column names when specifying order for our query results, like so:

In [31]:
%%sql
SELECT name, migration_rate FROM FACTS
ORDER BY migration_rate desc;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[('Qatar', 22.39),
 ('American Samoa', 21.13),
 ('Micronesia, Federated States of', 20.93),
 ('Syria', 19.79),
 ('Tonga', 17.84),
 ('British Virgin Islands', 17.28),
 ('Luxembourg', 17.16),
 ('Cayman Islands', 14.4),
 ('Singapore', 14.05),
 ('Nauru', 13.63),
 ('Jordan', 13.24),
 ('Bahrain', 13.09),
 ('Maldives', 12.68),
 ('United Arab Emirates', 12.36),
 ('Anguilla', 12.18),
 ('South Sudan', 11.47),
 ('Turks and Caicos Islands', 9.94),
 ('Samoa', 9.78),
 ('Moldova', 9.67),
 ('Cyprus', 9.48),
 ('Saint Vincent and the Grenadines', 9.17),
 ('Aruba', 8.92),
 ('Sao Tome and Principe', 8.63),
 ('Somalia', 8.49),
 ('Saint Pierre and Miquelon', 8.49),
 ('Spain', 8.31),
 ('El Salvador', 8.28),
 ('Puerto Rico', 8.15),
 ('Guyana', 8.06),
 ('San Marino', 8.03),
 ('Libya', 7.8),
 ('Virgin Islands', 7.67),
 ('Lesotho', 7.36),
 ('Norway', 7.25),
 ('Northern Mariana Islands', 7.16),
 ('Tuvalu', 6.81),
 ('Fiji', 6.75),
 ('Sint Maarten', 6.63),
 ('Isle of Man', 6.56),
 ('Guam', 6.34),
 ('Lithuania', 6.27),
 ('Latvia', 6.26),
 ('Trinidad and Tobago', 6.25),
 ('Djibouti', 6.06),
 ('Greenland', 5.98),
 ('Congo, Republic of the', 5.9),
 ('Belgium', 5.87),
 ('Armenia', 5.8),
 ('Canada', 5.66),
 ('Australia', 5.65),
 ('Austria', 5.56),
 ('Sweden', 5.42),
 ('Dominica', 5.38),
 ('Kyrgyzstan', 5.22),
 ('Liechtenstein', 5.08),
 ('Wallis and Futuna', 5.06),
 ('Marshall Islands', 4.83),
 ('Switzerland', 4.74),
 ('Jamaica', 4.66),
 ('Botswana', 4.56),
 ('Iceland', 4.43),
 ('Sudan', 4.29),
 ('Italy', 4.1),
 ('Ireland', 4.09),
 ('New Caledonia', 4.01),
 ('Nepal', 3.86),
 ('Timor-Leste', 3.86),
 ('United States', 3.86),
 ('Monaco', 3.83),
 ('Jersey', 3.76),
 ('Cuba', 3.66),
 ('Estonia', 3.6),
 ('Chad', 3.45),
 ('Macau', 3.37),
 ('Morocco', 3.36),
 ('Albania', 3.3),
 ('Gibraltar', 3.28),
 ('Grenada', 3.13),
 ('Finland', 3.1),
 ('Nicaragua', 3.0),
 ('Saint Lucia', 2.93),
 ('Kiribati', 2.87),
 ('Sierra Leone', 2.77),
 ('Haiti', 2.76),
 ('Georgia', 2.7),
 ('Portugal', 2.67),
 ('United Kingdom', 2.54),
 ('Comoros', 2.53),
 ('Peru', 2.53),
 ('European Union', 2.5),
 ('Brunei', 2.43),
 ('South Africa', 2.42),
 ('Uzbekistan', 2.37),
 ('Czech Republic', 2.33),
 ('Greece', 2.32),
 ('Guernsey', 2.32),
 ('Mali', 2.26),
 ('Ukraine', 2.25),
 ('Israel', 2.24),
 ('Antigua and Barbuda', 2.21),
 ('New Zealand', 2.21),
 ('Denmark', 2.2),
 ('Turkey', 2.16),
 ('Gambia, The', 2.12),
 ('Philippines', 2.09),
 ('Gabon', 2.03),
 ('Ghana', 2.02),
 ('Malta', 1.98),
 ('Mozambique', 1.98),
 ('Guatemala', 1.97),
 ('Netherlands', 1.95),
 ('Dominican Republic', 1.91),
 ('Bermuda', 1.88),
 ('Turkmenistan', 1.84),
 ('Solomon Islands', 1.75),
 ('Tunisia', 1.73),
 ('Russia', 1.69),
 ('Mexico', 1.68),
 ('Hong Kong', 1.68),
 ('Iraq', 1.62),
 ('Senegal', 1.59),
 ('Kuwait', 1.58),
 ('Pakistan', 1.54),
 ('Afghanistan', 1.51),
 ('Vanuatu', 1.47),
 ('Curacao', 1.4),
 ('Croatia', 1.39),
 ('Sri Lanka', 1.35),
 ('Hungary', 1.33),
 ('Germany', 1.24),
 ('Saint Kitts and Nevis', 1.21),
 ('Honduras', 1.16),
 ('Indonesia', 1.16),
 ('Tajikistan', 1.15),
 ('Lebanon', 1.1),
 ('France', 1.09),
 ('Laos', 1.09),
 ('Seychelles', 1.0),
 ('Yemen', 1.0),
 ('Algeria', 0.92),
 ('Uruguay', 0.9),
 ('Taiwan', 0.89),
 ('Rwanda', 0.85),
 ('Mongolia', 0.84),
 ('French Polynesia', 0.84),
 ('Costa Rica', 0.83),
 ('Mauritania', 0.83),
 ('Uganda', 0.74),
 ('Palau', 0.71),
 ('Belarus', 0.7),
 ('Zambia', 0.68),
 ('Colombia', 0.64),
 ('Cabo Verde', 0.63),
 ('Bolivia', 0.62),
 ('Niger', 0.56),
 ('Suriname', 0.56),
 ('Saudi Arabia', 0.55),
 ('Tanzania', 0.54),
 ('Macedonia', 0.48),
 ('Angola', 0.46),
 ('Bangladesh', 0.46),
 ('Poland', 0.46),
 ('China', 0.44),
 ('Oman', 0.43),
 ('Kazakhstan', 0.41),
 ('Bosnia and Herzegovina', 0.38),
 ('Slovenia', 0.37),
 ('Chile', 0.34),
 ('Malaysia', 0.33),
 ('Cambodia', 0.32),
 ('Barbados', 0.3),
 ('Vietnam', 0.3),
 ('Bulgaria', 0.29),
 ('Burma', 0.28),
 ('Panama', 0.28),
 ('Congo, Democratic Republic of the', 0.27),
 ('Romania', 0.24),
 ('Ethiopia', 0.22),
 ('Kenya', 0.22),
 ('Nigeria', 0.22),
 ('Egypt', 0.19),
 ('Cameroon', 0.15),
 ('Brazil', 0.14),
 ('Iran', 0.07),
 ('Paraguay', 0.07),
 ('India', 0.04),
 ('Korea, North', 0.04),
 ('Slovakia', 0.04),
 ('Andorra', 0.0),
 ('Argentina', 0.0),
 ('Azerbaijan', 0.0),
 ('Bahamas, The', 0.0),
 ('Belize', 0.0),
 ('Benin', 0.0),
 ('Bhutan', 0.0),
 ('Burkina Faso', 0.0),
 ('Burundi', 0.0),
 ('Central African Republic', 0.0),
 ("Cote d'Ivoire", 0.0),
 ('Ecuador', 0.0),
 ('Equatorial Guinea', 0.0),
 ('Eritrea', 0.0),
 ('Guinea', 0.0),
 ('Guinea-Bissau', 0.0),
 ('Japan', 0.0),
 ('Korea, South', 0.0),
 ('Liberia', 0.0),
 ('Madagascar', 0.0),
 ('Malawi', 0.0),
 ('Mauritius', 0.0),
 ('Namibia', 0.0),
 ('Papua New Guinea', 0.0),
 ('Serbia', 0.0),
 ('Swaziland', 0.0),
 ('Thailand', 0.0),
 ('Togo', 0.0),
 ('Venezuela', 0.0),
 ('Zimbabwe', 0.0),
 ('Faroe Islands', 0.0),
 ('Montserrat', 0.0),
 ('Saint Helena, Ascension, and Tristan da Cunha', 0.0),
 ('Gaza Strip', 0.0),
 ('West Bank', 0.0),
 ('Kosovo', None),
 ('Montenegro', None),
 ('Holy See (Vatican City)', None),
 ('Ashmore and Cartier Islands', None),
 ('Christmas Island', None),
 ('Cocos (Keeling) Islands', None),
 ('Coral Sea Islands', None),
 ('Heard Island and McDonald Islands', None),
 ('Norfolk Island', None),
 ('Clipperton Island', None),
 ('French Southern and Antarctic Lands', None),
 ('Saint Barthelemy', None),
 ('Saint Martin', None),
 ('Cook Islands', None),
 ('Niue', None),
 ('Tokelau', None),
 ('Bouvet Island', None),
 ('Jan Mayen', None),
 ('Svalbard', None),
 ('Akrotiri', None),
 ('British Indian Ocean Territory', None),
 ('Dhekelia', None),
 ('Falkland Islands (Islas Malvinas)', None),
 ('Pitcairn Islands', None),
 ('South Georgia and South Sandwich Islands', None),
 ('Navassa Island', None),
 ('Wake Island', None),
 ('United States Pacific Island Wildlife Refuges', None),
 ('Antarctica', None),
 ('Paracel Islands', None),
 ('Spratly Islands', None),
 ('Western Sahara', None),
 ('Arctic Ocean', None),
 ('Atlantic Ocean', None),
 ('Indian Ocean', None),
 ('Pacific Ocean', None),
 ('Southern Ocean', None),
 ('World', None)]

There is a handy shortcut we can use in our queries which lets us skip the column names, and instead use the order in which the columns appear in the `SELECT` clause. In this instance, `migration_rate` is the second column in our `SELECT` clause so we can just use `2` instead of the column name:

In [38]:
%%sql
SELECT name, migration_rate FROM FACTS
ORDER BY 2 desc;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[('Qatar', 22.39),
 ('American Samoa', 21.13),
 ('Micronesia, Federated States of', 20.93),
 ('Syria', 19.79),
 ('Tonga', 17.84),
 ('British Virgin Islands', 17.28),
 ('Luxembourg', 17.16),
 ('Cayman Islands', 14.4),
 ('Singapore', 14.05),
 ('Nauru', 13.63),
 ('Jordan', 13.24),
 ('Bahrain', 13.09),
 ('Maldives', 12.68),
 ('United Arab Emirates', 12.36),
 ('Anguilla', 12.18),
 ('South Sudan', 11.47),
 ('Turks and Caicos Islands', 9.94),
 ('Samoa', 9.78),
 ('Moldova', 9.67),
 ('Cyprus', 9.48),
 ('Saint Vincent and the Grenadines', 9.17),
 ('Aruba', 8.92),
 ('Sao Tome and Principe', 8.63),
 ('Somalia', 8.49),
 ('Saint Pierre and Miquelon', 8.49),
 ('Spain', 8.31),
 ('El Salvador', 8.28),
 ('Puerto Rico', 8.15),
 ('Guyana', 8.06),
 ('San Marino', 8.03),
 ('Libya', 7.8),
 ('Virgin Islands', 7.67),
 ('Lesotho', 7.36),
 ('Norway', 7.25),
 ('Northern Mariana Islands', 7.16),
 ('Tuvalu', 6.81),
 ('Fiji', 6.75),
 ('Sint Maarten', 6.63),
 ('Isle of Man', 6.56),
 ('Guam', 6.34),
 ('Lithuania', 6.27),
 ('Latvia', 6.26),
 ('Trinidad and Tobago', 6.25),
 ('Djibouti', 6.06),
 ('Greenland', 5.98),
 ('Congo, Republic of the', 5.9),
 ('Belgium', 5.87),
 ('Armenia', 5.8),
 ('Canada', 5.66),
 ('Australia', 5.65),
 ('Austria', 5.56),
 ('Sweden', 5.42),
 ('Dominica', 5.38),
 ('Kyrgyzstan', 5.22),
 ('Liechtenstein', 5.08),
 ('Wallis and Futuna', 5.06),
 ('Marshall Islands', 4.83),
 ('Switzerland', 4.74),
 ('Jamaica', 4.66),
 ('Botswana', 4.56),
 ('Iceland', 4.43),
 ('Sudan', 4.29),
 ('Italy', 4.1),
 ('Ireland', 4.09),
 ('New Caledonia', 4.01),
 ('Nepal', 3.86),
 ('Timor-Leste', 3.86),
 ('United States', 3.86),
 ('Monaco', 3.83),
 ('Jersey', 3.76),
 ('Cuba', 3.66),
 ('Estonia', 3.6),
 ('Chad', 3.45),
 ('Macau', 3.37),
 ('Morocco', 3.36),
 ('Albania', 3.3),
 ('Gibraltar', 3.28),
 ('Grenada', 3.13),
 ('Finland', 3.1),
 ('Nicaragua', 3.0),
 ('Saint Lucia', 2.93),
 ('Kiribati', 2.87),
 ('Sierra Leone', 2.77),
 ('Haiti', 2.76),
 ('Georgia', 2.7),
 ('Portugal', 2.67),
 ('United Kingdom', 2.54),
 ('Comoros', 2.53),
 ('Peru', 2.53),
 ('European Union', 2.5),
 ('Brunei', 2.43),
 ('South Africa', 2.42),
 ('Uzbekistan', 2.37),
 ('Czech Republic', 2.33),
 ('Greece', 2.32),
 ('Guernsey', 2.32),
 ('Mali', 2.26),
 ('Ukraine', 2.25),
 ('Israel', 2.24),
 ('Antigua and Barbuda', 2.21),
 ('New Zealand', 2.21),
 ('Denmark', 2.2),
 ('Turkey', 2.16),
 ('Gambia, The', 2.12),
 ('Philippines', 2.09),
 ('Gabon', 2.03),
 ('Ghana', 2.02),
 ('Malta', 1.98),
 ('Mozambique', 1.98),
 ('Guatemala', 1.97),
 ('Netherlands', 1.95),
 ('Dominican Republic', 1.91),
 ('Bermuda', 1.88),
 ('Turkmenistan', 1.84),
 ('Solomon Islands', 1.75),
 ('Tunisia', 1.73),
 ('Russia', 1.69),
 ('Mexico', 1.68),
 ('Hong Kong', 1.68),
 ('Iraq', 1.62),
 ('Senegal', 1.59),
 ('Kuwait', 1.58),
 ('Pakistan', 1.54),
 ('Afghanistan', 1.51),
 ('Vanuatu', 1.47),
 ('Curacao', 1.4),
 ('Croatia', 1.39),
 ('Sri Lanka', 1.35),
 ('Hungary', 1.33),
 ('Germany', 1.24),
 ('Saint Kitts and Nevis', 1.21),
 ('Honduras', 1.16),
 ('Indonesia', 1.16),
 ('Tajikistan', 1.15),
 ('Lebanon', 1.1),
 ('France', 1.09),
 ('Laos', 1.09),
 ('Seychelles', 1.0),
 ('Yemen', 1.0),
 ('Algeria', 0.92),
 ('Uruguay', 0.9),
 ('Taiwan', 0.89),
 ('Rwanda', 0.85),
 ('Mongolia', 0.84),
 ('French Polynesia', 0.84),
 ('Costa Rica', 0.83),
 ('Mauritania', 0.83),
 ('Uganda', 0.74),
 ('Palau', 0.71),
 ('Belarus', 0.7),
 ('Zambia', 0.68),
 ('Colombia', 0.64),
 ('Cabo Verde', 0.63),
 ('Bolivia', 0.62),
 ('Niger', 0.56),
 ('Suriname', 0.56),
 ('Saudi Arabia', 0.55),
 ('Tanzania', 0.54),
 ('Macedonia', 0.48),
 ('Angola', 0.46),
 ('Bangladesh', 0.46),
 ('Poland', 0.46),
 ('China', 0.44),
 ('Oman', 0.43),
 ('Kazakhstan', 0.41),
 ('Bosnia and Herzegovina', 0.38),
 ('Slovenia', 0.37),
 ('Chile', 0.34),
 ('Malaysia', 0.33),
 ('Cambodia', 0.32),
 ('Barbados', 0.3),
 ('Vietnam', 0.3),
 ('Bulgaria', 0.29),
 ('Burma', 0.28),
 ('Panama', 0.28),
 ('Congo, Democratic Republic of the', 0.27),
 ('Romania', 0.24),
 ('Ethiopia', 0.22),
 ('Kenya', 0.22),
 ('Nigeria', 0.22),
 ('Egypt', 0.19),
 ('Cameroon', 0.15),
 ('Brazil', 0.14),
 ('Iran', 0.07),
 ('Paraguay', 0.07),
 ('India', 0.04),
 ('Korea, North', 0.04),
 ('Slovakia', 0.04),
 ('Andorra', 0.0),
 ('Argentina', 0.0),
 ('Azerbaijan', 0.0),
 ('Bahamas, The', 0.0),
 ('Belize', 0.0),
 ('Benin', 0.0),
 ('Bhutan', 0.0),
 ('Burkina Faso', 0.0),
 ('Burundi', 0.0),
 ('Central African Republic', 0.0),
 ("Cote d'Ivoire", 0.0),
 ('Ecuador', 0.0),
 ('Equatorial Guinea', 0.0),
 ('Eritrea', 0.0),
 ('Guinea', 0.0),
 ('Guinea-Bissau', 0.0),
 ('Japan', 0.0),
 ('Korea, South', 0.0),
 ('Liberia', 0.0),
 ('Madagascar', 0.0),
 ('Malawi', 0.0),
 ('Mauritius', 0.0),
 ('Namibia', 0.0),
 ('Papua New Guinea', 0.0),
 ('Serbia', 0.0),
 ('Swaziland', 0.0),
 ('Thailand', 0.0),
 ('Togo', 0.0),
 ('Venezuela', 0.0),
 ('Zimbabwe', 0.0),
 ('Faroe Islands', 0.0),
 ('Montserrat', 0.0),
 ('Saint Helena, Ascension, and Tristan da Cunha', 0.0),
 ('Gaza Strip', 0.0),
 ('West Bank', 0.0),
 ('Kosovo', None),
 ('Montenegro', None),
 ('Holy See (Vatican City)', None),
 ('Ashmore and Cartier Islands', None),
 ('Christmas Island', None),
 ('Cocos (Keeling) Islands', None),
 ('Coral Sea Islands', None),
 ('Heard Island and McDonald Islands', None),
 ('Norfolk Island', None),
 ('Clipperton Island', None),
 ('French Southern and Antarctic Lands', None),
 ('Saint Barthelemy', None),
 ('Saint Martin', None),
 ('Cook Islands', None),
 ('Niue', None),
 ('Tokelau', None),
 ('Bouvet Island', None),
 ('Jan Mayen', None),
 ('Svalbard', None),
 ('Akrotiri', None),
 ('British Indian Ocean Territory', None),
 ('Dhekelia', None),
 ('Falkland Islands (Islas Malvinas)', None),
 ('Pitcairn Islands', None),
 ('South Georgia and South Sandwich Islands', None),
 ('Navassa Island', None),
 ('Wake Island', None),
 ('United States Pacific Island Wildlife Refuges', None),
 ('Antarctica', None),
 ('Paracel Islands', None),
 ('Spratly Islands', None),
 ('Western Sahara', None),
 ('Arctic Ocean', None),
 ('Atlantic Ocean', None),
 ('Indian Ocean', None),
 ('Pacific Ocean', None),
 ('Southern Ocean', None),
 ('World', None)]

You can use this shortcut in either the `ORDER BY` or `GROUP BY` clauses. Be mindful that you want to ensure your queries are still readable, so typing the full column name may be better for more complex queries.

Let's use what we've learned to produce a list of the top 10 capital cities by population. Remember that `capital` is a boolean column containing `1` or `0`, depending on whether a city is a capital or not.

Write a query that returns the 10 capital cities with the highest population ranked from biggest to smallest population.
- You should include the following columns, in order:
    - capital_city, the name of the city.
    - country, the name of the country the city is from.
    - population, the population of the city.

Because we are not interested in countries from `facts` that don't have corresponding `cities` in cities, we should use an `INNER JOIN`.

In [50]:
%%sql
SELECT c.name capital_city, 
        f.name country,
        c.population population
FROM facts f
INNER JOIN cities c ON c.facts_id = f.id 
WHERE c.capital = 1
ORDER BY 3 DESC
LIMIT 10;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[('Tokyo', 'Japan', 37217000),
 ('New Delhi', 'India', 22654000),
 ('Mexico City', 'Mexico', 20446000),
 ('Beijing', 'China', 15594000),
 ('Dhaka', 'Bangladesh', 15391000),
 ('Buenos Aires', 'Argentina', 13528000),
 ('Manila', 'Philippines', 11862000),
 ('Moscow', 'Russia', 11621000),
 ('Cairo', 'Egypt', 11169000),
 ('Jakarta', 'Indonesia', 9769000)]

## SUBQUERIES

Subqueries can be used to substitute parts of queries, allowing us to find the answers to more complex questions. We can also join to the result of a subquery, just like we could a table.

Here's an example of a using a join and a subquery to produce a table of countries and their capital cities.

In [55]:
%%sql
SELECT f.name country, c.name capital_city 
FROM facts f
INNER JOIN (
        SELECT * FROM cities
        WHERE capital = 1
        ) c ON c.facts_id = f.id
LIMIT 10;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[('Aruba', 'Oranjestad'),
 ('Antigua and Barbuda', "Saint John'S"),
 ('United Arab Emirates', 'Abu Dhabi'),
 ('Afghanistan', 'Kabul'),
 ('Algeria', 'Algiers'),
 ('Azerbaijan', 'Baku'),
 ('Albania', 'Tirana'),
 ('Armenia', 'Yerevan'),
 ('Andorra', 'Andorra La Vella'),
 ('Angola', 'Luanda')]

The important thing to remember is that the result of any subquery is always calculated first, so we read from the inside out.

- The subquery, is calculated first. This simple query selects all columns from cities, filtering rows that are marked as capital cities by having a value for capital of 1.
- The `INNER JOIN` joins the subquery result, aliased as `c`, to the `facts` table based on the `ON` clause.
- Two columns are selected from the results of the join:
    - f.name, aliased as country.
    - c.name, aliased as capital_city.
- The results are limited to the first 10 rows.

Using this example as a model, we'll write a similar query to find the capital cities with populations of over 10 million.

Using a join and a subquery, write a query that returns capital cities with populations of over 10 million ordered from largest to smallest. Include the following columns:
- `capital_city` - the name of the city.
- `country` - the name of the country the city is the capital of.
- `population` - the population of the city.

In [60]:
%%sql
SELECT c.name capital_city, f.name country, c.population
FROM facts f
INNER JOIN (
        SELECT * FROM cities
        WHERE capital = 1 AND population > 10000000
        ) c ON c.facts_id = f.id
ORDER BY 3 DESC;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[('Tokyo', 'Japan', 37217000),
 ('New Delhi', 'India', 22654000),
 ('Mexico City', 'Mexico', 20446000),
 ('Beijing', 'China', 15594000),
 ('Dhaka', 'Bangladesh', 15391000),
 ('Buenos Aires', 'Argentina', 13528000),
 ('Manila', 'Philippines', 11862000),
 ('Moscow', 'Russia', 11621000),
 ('Cairo', 'Egypt', 11169000)]

## Challenge - complex queries 

When you're writing complex queries with joins and subqueries, it helps to follow this process:

- Think about what data you need in your final output
- Work out which tables you'll need to join, and whether you will need to join to a subquery.
    - If you need to join to a subquery, write the subquery first.
- Then start writing your SELECT clause, followed by the join and any other clauses you will need.
- Don't be afraid to write your query in steps, running it as you go— for instance you can run your subquery as a 'stand alone' query first to make sure it looks like you want before writing the outer query.
We will be writing a query to `find the countries where the urban center (city) population is more than half of the country's total population`. For expected results, we rounded to six decimal places; however, when running your query, don't worry about rounding the `urban_pct` column.

To help you out, the query you will write will include:

- A join to a subquery.
- A subquery to make a calculation.
- An aggregate function.
- A WHERE clause.
- A CAST expression.

The query should include:

The following columns, in order:
- `country`, the name of the country.
- `urban_pop`, the sum of the population in major urban areas belonging to that country.
- `total_pop`, the total population of the country.
- `urban_pct`, the percentage of the population within urban areas, calculated by dividing urban_pop by total_pop.

Only countries that have an `urban_pct` greater than 0.5.

Rows should be sorted by `urban_pct` in ascending order.

Define `urban_pop` within your subquery.

In [69]:
%%sql
SELECT f.name country,
        c.urban_pop,
        f.population total_pop,
        (c.urban_pop / CAST(f.population AS FLOAT)) urban_pct 
FROM facts f
INNER JOIN (
        SELECT facts_id, SUM(population) urban_pop 
        FROM cities
        GROUP BY 1
        ) c ON c.facts_id = f.id
WHERE urban_pct > .5
ORDER BY 4 ASC;

 * sqlite:///factbook-join.db
   sqlite:///factbook.db
Done.

[('Uruguay', 1672000, 3341893, 0.5003152404939356),
 ('Congo, Republic of the', 2445000, 4755097, 0.5141850944365594),
 ('Brunei', 241000, 429646, 0.5609269026128487),
 ('New Caledonia', 157000, 271615, 0.5780240413821034),
 ('Virgin Islands', 60000, 103574, 0.5792959623071428),
 ('Falkland Islands (Islas Malvinas)', 2000, 3361, 0.5950609937518596),
 ('Djibouti', 496000, 828324, 0.5987995035758954),
 ('Australia', 13789000, 22751014, 0.6060828761302683),
 ('Iceland', 206000, 331918, 0.6206352171319423),
 ('Israel', 5226000, 8049314, 0.6492478737939655),
 ('United Arab Emirates', 3903000, 5779760, 0.6752875551926032),
 ('Puerto Rico', 2475000, 3598357, 0.6878139106264332),
 ('Bahamas, The', 254000, 324597, 0.7825087724162577),
 ('Kuwait', 2406000, 2788534, 0.8628189579183901),
 ('Saint Pierre and Miquelon', 5000, 5657, 0.8838607035531201),
 ('Guam', 169000, 161785, 1.0445962233828847),
 ('Northern Mariana Islands', 56000, 52344, 1.0698456365581537),
 ('American Samoa', 64000, 54343, 1.1777045801667188)]

In this mission we learned:

- The difference between inner and left joins.
- How to choose which join is appropriate for your task.
- Using joins with subqueries, aggregate functions and other SQL techniques.